//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.BaxterMoveit
{
    public class BaxterArmJoints : Message
    {
        public const string RosMessageName = "baxter_moveit/BaxterArmJoints";

        public double[] angles;

        public BaxterArmJoints()
        {
            this.angles = new double[0];
        }

        public BaxterArmJoints(double[] angles)
        {
            this.angles = angles;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            
            listOfSerializations.Add(BitConverter.GetBytes(angles.Length));
            foreach(var entry in angles)
                listOfSerializations.Add(BitConverter.GetBytes(entry));

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            
            var anglesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.angles= new double[anglesArrayLength];
            for(var i = 0; i < anglesArrayLength; i++)
            {
                this.angles[i] = BitConverter.ToDouble(data, offset);
                offset += 8;
            }

            return offset;
        }

        public override string ToString()
        {
            return "BaxterArmJoints: " +
            "\nangles: " + System.String.Join(", ", angles.ToList());
        }
    }
}
