//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.BaxterHrc
{
    public class ActionServiceResponse : Message
    {
        public const string RosMessageName = "baxter_hrc/ActionService";

        public string operation;
        public string arm;
        public Moveit.RobotTrajectory[] trajectories;

        public ActionServiceResponse()
        {
            this.operation = "";
            this.arm = "";
            this.trajectories = new Moveit.RobotTrajectory[0];
        }

        public ActionServiceResponse(string operation, string arm, Moveit.RobotTrajectory[] trajectories)
        {
            this.operation = operation;
            this.arm = arm;
            this.trajectories = trajectories;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.Add(SerializeString(this.operation));
            listOfSerializations.Add(SerializeString(this.arm));
            
            listOfSerializations.Add(BitConverter.GetBytes(trajectories.Length));
            foreach(var entry in trajectories)
                listOfSerializations.Add(entry.Serialize());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            var operationStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.operation = DeserializeString(data, offset, operationStringBytesLength);
            offset += operationStringBytesLength;
            var armStringBytesLength = DeserializeLength(data, offset);
            offset += 4;
            this.arm = DeserializeString(data, offset, armStringBytesLength);
            offset += armStringBytesLength;
            
            var trajectoriesArrayLength = DeserializeLength(data, offset);
            offset += 4;
            this.trajectories= new Moveit.RobotTrajectory[trajectoriesArrayLength];
            for(var i = 0; i < trajectoriesArrayLength; i++)
            {
                this.trajectories[i] = new Moveit.RobotTrajectory();
                offset = this.trajectories[i].Deserialize(data, offset);
            }

            return offset;
        }

        public override string ToString()
        {
            return "ActionServiceResponse: " +
            "\noperation: " + operation.ToString() +
            "\narm: " + arm.ToString() +
            "\ntrajectories: " + System.String.Join(", ", trajectories.ToList());
        }
    }
}
