//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using RosMessageGeneration;

namespace RosMessageTypes.BaxterHrc
{
    public class JointStateServiceResponse : Message
    {
        public const string RosMessageName = "baxter_hrc/JointStateService";

        public Sensor.JointState joint_state_msg;

        public JointStateServiceResponse()
        {
            this.joint_state_msg = new Sensor.JointState();
        }

        public JointStateServiceResponse(Sensor.JointState joint_state_msg)
        {
            this.joint_state_msg = joint_state_msg;
        }
        public override List<byte[]> SerializationStatements()
        {
            var listOfSerializations = new List<byte[]>();
            listOfSerializations.AddRange(joint_state_msg.SerializationStatements());

            return listOfSerializations;
        }

        public override int Deserialize(byte[] data, int offset)
        {
            offset = this.joint_state_msg.Deserialize(data, offset);

            return offset;
        }

        public override string ToString()
        {
            return "JointStateServiceResponse: " +
            "\njoint_state_msg: " + joint_state_msg.ToString();
        }
    }
}
